### ISSUE TITLE
close modal automatically after success

### ISSUE THREAD

**Issue by akinolu52** [iamraphson/react-ravepayment#30]
is there a method i can call to close the modal after successful transaction

**Comment by akinolu52** [comment]
any help @iamraphson

**Comment by Yawmiej** [comment]
@akinolu52 were you able to work this out? I am currently facing the same issue

**Comment by iamraphson** [comment]
@Yawmiej @akinolu52 i think the user have to close it manually

**Comment by CodebyOmar** [comment]
on the documentation you can pass a callback function where by you can close the modal immediately after payment.

```
callback: function(response) {
    var txref = response.data.txRef; // collect txRef returned and pass to a  server page to complete status check.
    console.log("This is the response returned after a charge", response);
    if (
        response.data.chargeResponseCode == "00" ||
        response.data.chargeResponseCode == "0"
    ) {
        // redirect to a success page
    } else {
        // redirect to a failure page.
    }

    x.close(); // use this to close the modal immediately after payment.
}
```

**Suggestion**
Since most people want the auto-close feature, you can include a prop ```autoClose``` of boolean type. Then call close modal in the callback function like in the above code ```x.close()```. Where ```x``` is returned after calling ```window.getpaidSetup(raveOptions)```.

 Any other thing can be handled on close or on success. @iamraphson
